[project]
name = "goszakup-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "openai>=2.23.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
